"""Adicionando entidades: Pessoa e Conta

Revision ID: 0d505c6bfada
Revises: 
Create Date: 2023-12-18 02:15:53.045293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d505c6bfada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fl_ativo', sa.Boolean(), nullable=False),
    sa.Column('limite_saque_diario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
