"""renaming transction reciver_id -> origin account and check contraint on balance

Revision ID: 11ba600c4d43
Revises: 796cbec9b5ac
Create Date: 2024-06-14 17:38:21.616307

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "11ba600c4d43"
down_revision = "796cbec9b5ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("origin_account_id", sa.BigInteger(), nullable=False)
        )
        batch_op.drop_constraint("transactions_ibfk_2", type_="foreignkey")
        batch_op.create_foreign_key(None, "accounts", ["origin_account_id"], ["id"])
        batch_op.drop_column("reciver_id")

    # ### end Alembic commands ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "check_accounts_balance_positive", "balance > 0"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "reciver_id",
                mysql.BIGINT(display_width=20),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "transactions_ibfk_2", "accounts", ["reciver_id"], ["id"]
        )
        batch_op.drop_column("origin_account_id")

    # ### end Alembic commands ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_constraint("check_accounts_balance_positive")
