"""Cpf unico obrigatorio

Revision ID: b86f5218f5f4
Revises: 0d505c6bfada
Create Date: 2023-12-21 16:36:25.424534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86f5218f5f4'
down_revision = '0d505c6bfada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_conta', sa.Integer(), nullable=False))

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_column('tipo_conta')

    # ### end Alembic commands ###
